name: pageloader
version: 3.0.0-dev
authors:
  - Marc Fisher II (emeritus) <fisherii@google.com>
  - Max Kim <maxkim@google.com>
  - Matt Staats (emeritus)
description:
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.
homepage: https://github.com/google/pageloader
environment:
  sdk: '>=2.0.0-dev.48 <2.0.0'
dependencies:
  build: '^0.12.0'
  built_value: '^5.1.0'
  matcher: '^0.12.0+1'
  quiver: '>=0.29.0 <0.30.0'
  source_gen: '^0.8.0'
  webdriver: '^2.0.0-beta'
dev_dependencies:
  build_config: ">=0.2.4 <2.0.0"
  build_runner: '^0.8.7'
  built_value_generator: '^5.4.0'
  path: '^1.3.6'
  test: '^0.12.3+9'
