name: pageloader

version: 4.0.0

authors:
  - Marc Fisher II (emeritus)
  - Max Kim <maxkim@google.com>
  - Matt Staats <staats@google.com>

description:
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.

homepage: https://github.com/google/pageloader

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.8.0
  build: ^2.0.2
  built_value: ^8.0.6
  build_config: ^1.0.0
  js: ^0.6.3
  matcher: ^0.12.10
  quiver: ^3.0.1
  source_gen: ^1.0.1
  webdriver: ^3.0.0
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.0.4
  built_value_generator: ^8.0.6
  path: ^1.8.0
  test: ^1.17.5
