name: pageloader
version: 1.3.0
author: Marc Fisher II
description: Supports the creation of page objects that can be shared between in-browser tests and WebDriver tests.
environment:
  sdk: '>=1.9.0-dev.4.0 <2.0.0'
dependencies:
  matcher: '^0.11.4'
  sync_webdriver:
    path: ../../dart-sync-webdriver
dev_dependencies:
  browser: '^0.10.0+2'
  path: '^1.3.2'
  unittest: '^0.11.5'
