name: pageloader
version: 2.0.0-pre.1
author: Google, Inc.
description: >
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.
homepage: https://github.com/google/pageloader
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  matcher: '^0.11.4+1'
  sync_webdriver: '^1.1.4+1'
  webdriver: '^0.10.0-pre.2'
dev_dependencies:
  browser: '^0.10.0+2'
  path: '^1.3.3'
  unittest: '^0.11.5+4'
