name: pageloader
version: 1.2.3
author: Marc Fisher II
description: Supports the creation of page objects that can be shared between in-browser tests and WebDriver tests.
environment:
  sdk: '>=1.8.0-dev.0.0 <2.0.0'
dependencies:
  sync_webdriver:
    path: ../../dart-sync-webdriver
dev_dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  path: '>=1.3.0 <2.0.0'
  unittest: '>=0.11.3 <0.12.0'
