name: pageloader
version: 2.2.2
author: Marc Fisher II <fisherii@google.com>
description: >
  Supports the creation of page objects that can be shared between in-browser tests
  and WebDriver tests.
homepage: https://github.com/google/pageloader
environment:
  sdk: '>=1.11.0 <2.0.0'
dependencies:
  stack_trace: '^1.6.0'
  webdriver: '^1.2.0'
dev_dependencies:
  path: '^1.3.6'
  test: '^0.12.3+9'
